# Generated by Django 3.0.14 on 2022-12-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquetes',
            name='servicios',
        ),
        migrations.AddField(
            model_name='tiposservicios',
            name='paquetes',
            field=models.ManyToManyField(blank=True, max_length=150, to='servicios.Paquetes', verbose_name='Paquetes'),
        ),
    ]
