# Generated by Django 3.0.14 on 2022-12-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20221226_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=55, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
            },
        ),
        migrations.AlterField(
            model_name='paquetes',
            name='entregables',
            field=models.ManyToManyField(blank=True, to='servicios.Entregables', verbose_name='Entregables'),
        ),
        migrations.DeleteModel(
            name='TiposServicios',
        ),
        migrations.AddField(
            model_name='servicios',
            name='paquetes',
            field=models.ManyToManyField(blank=True, to='servicios.Paquetes', verbose_name='Paquetes'),
        ),
    ]
