# Generated by Django 3.0.14 on 2022-12-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20221227_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='precio',
            field=models.IntegerField(null=True, verbose_name='Precio'),
        ),
    ]
